# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DownloadDocount', models.IntegerField(default=0, verbose_name='访问次数')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('Datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('path', models.CharField(max_length=32, verbose_name='下载路径')),
                ('name', models.CharField(default='', max_length=32, verbose_name='文件名')),
                ('Filesize', models.CharField(max_length=32, verbose_name='文件大小')),
                ('PCIP', models.CharField(default='', max_length=32, verbose_name='IP地址')),
            ],
        ),
    ]
